version = 0.1
[default.deploy.parameters]
stack_name = "apigateway-backend-integration"
resolve_s3 = true
s3_prefix = "apigateway-backend-integration"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "HttpUrl=\"https://custom-backend-url\" ACMCertificateArn=\"arn:aws:acm:us-east-1:XXXXXX:certificate/XXXXXXXXXXX\" CustomDomainName=\"web.xxxxxx.com\" CustomHostedZoneId=\"XXXXXXXX\""
image_repositories = []
confirm_changeset = true