version = 0.1
[default.deploy.parameters]
stack_name = "apigateway-backend-integration"
resolve_s3 = true
s3_prefix = "apigateway-backend-integration"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "HttpUrl=\"https://backend-custom-url.com\""
image_repositories = []
