version = 0.1
[default.deploy.parameters]
stack_name = "lambda-function-versioning-sam"
resolve_s3 = true
s3_prefix = "lambda-function-versioning-sam"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
